services:
  school_sys:
    build: .
    ports:
      - "8000:8000"
    volumes:
      # Permite que el entorno de trabajo sea la ruta que en dode ejecut√≥
      # el << docker-compose up --build >>
      - .:/app
    environment:
      - PYTHONUNBUFFERED=1
